[package]
name = "cinatoken-ring-transition-runner"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
bytes.workspace = true
ed25519-dalek.workspace = true
getrandom.workspace = true
hmac.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
same-file.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
zeroize.workspace = true

[target.'cfg(windows)'.dependencies]
hyper-tls.workspace = true
native-tls.workspace = true

[target.'cfg(not(windows))'.dependencies]
hyper-rustls.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "cinatoken-ring-transition-runner"
path = "src/main.rs"
