//! Golden parity test: the ported default ratio/price tables in
//! `cinatoken_core::default_ratios` must match Go's `setting/ratio_setting`
//! `defaultModelRatio` / `defaultModelPrice` / ... maps exactly.
//!
//! The fixture `fixtures/default_ratios_go.tsv` is ground truth generated by
//! running the real Go maps (including the `RMB = 500/7.3` conversion) and
//! dumping `table<TAB>model<TAB>%.17g` rows — see the scratchpad generator
//! and the `go-ground-truth-golden-fixtures` memory. These are ~250
//! hand-transcribed billing entries, the highest transcription-error risk in
//! the port, so the test compares full key sets and exact (round-trippable)
//! values in both directions.

use std::collections::HashMap;

use cinatoken_core::default_ratios::{
    DEFAULT_AUDIO_COMPLETION_RATIO, DEFAULT_AUDIO_RATIO, DEFAULT_CACHE_RATIO,
    DEFAULT_COMPLETION_RATIO, DEFAULT_CREATE_CACHE_RATIO, DEFAULT_IMAGE_RATIO, DEFAULT_MODEL_PRICE,
    DEFAULT_MODEL_RATIO,
};

fn rust_table(name: &str) -> &'static [(&'static str, f64)] {
    match name {
        "modelRatio" => DEFAULT_MODEL_RATIO,
        "modelPrice" => DEFAULT_MODEL_PRICE,
        "audioRatio" => DEFAULT_AUDIO_RATIO,
        "audioCompletionRatio" => DEFAULT_AUDIO_COMPLETION_RATIO,
        "completionRatio" => DEFAULT_COMPLETION_RATIO,
        "imageRatio" => DEFAULT_IMAGE_RATIO,
        "cacheRatio" => DEFAULT_CACHE_RATIO,
        "createCacheRatio" => DEFAULT_CREATE_CACHE_RATIO,
        other => panic!("unknown table {other}"),
    }
}

#[test]
fn default_tables_match_go() {
    let tsv = include_str!("fixtures/default_ratios_go.tsv");

    // Group the Go ground truth by table.
    let mut go: HashMap<&str, HashMap<&str, f64>> = HashMap::new();
    for line in tsv.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let mut it = line.split('\t');
        let table = it.next().expect("table column");
        let model = it.next().expect("model column");
        let value: f64 = it
            .next()
            .expect("value column")
            .parse()
            .expect("value parses as f64");
        assert!(
            go.entry(table).or_default().insert(model, value).is_none(),
            "duplicate Go key {model} in table {table}"
        );
    }

    let tables = [
        "modelRatio",
        "modelPrice",
        "audioRatio",
        "audioCompletionRatio",
        "completionRatio",
        "imageRatio",
        "cacheRatio",
        "createCacheRatio",
    ];

    // Known, deliberate divergences where Rust does NOT match Go. Go evaluates
    // these as untyped-constant *integer* division (`1 / 1000 * USD` -> `0/1000
    // -> 0 * 500 -> 0`), silently making the model free; the Rust port uses the
    // intended float ratio. Documented finding, not a transcription error.
    // (model, go_value, rust_value)
    let known_divergences: &[(&str, &str, f64, f64)] = &[
        ("modelRatio", "llama-3-sonar-large-32k-chat", 0.0, 0.5),
        ("modelRatio", "llama-3-sonar-large-32k-online", 0.0, 0.5),
    ];
    let allow = |table: &str, key: &str| -> Option<(f64, f64)> {
        known_divergences
            .iter()
            .find(|(t, k, _, _)| *t == table && *k == key)
            .map(|(_, _, g, r)| (*g, *r))
    };

    let mut problems: Vec<String> = Vec::new();

    for t in tables {
        let go_map = go.get(t).unwrap_or_else(|| panic!("fixture missing table {t}"));
        let slice = rust_table(t);

        let mut rust_map: HashMap<&str, f64> = HashMap::with_capacity(slice.len());
        for (k, v) in slice {
            if rust_map.insert(*k, *v).is_some() {
                problems.push(format!("table {t}: duplicate Rust key {k:?}"));
            }
        }

        // Every Go entry must be present in Rust with the same value. Compare
        // with a tight relative epsilon rather than bit-exactly: Go folds the
        // RMB-derived entries (`0.120 * RMB`, `RMB = 500/7.3`) in
        // arbitrary-precision untyped-constant arithmetic with a single final
        // rounding, while Rust evaluates the identical expression in f64 (an
        // extra rounding through `RMB`). That difference is ~1 ULP (relative
        // ~2e-16), operationally zero for integer-quota billing. 1e-9 still
        // catches any real transcription error (wrong digit, missing/extra).
        for (k, v) in go_map {
            match rust_map.get(*k) {
                Some(rv) => {
                    if let Some((g, r)) = allow(t, k) {
                        if (g - *v).abs() < 1e-12 && (r - *rv).abs() < 1e-12 {
                            continue; // expected, documented divergence
                        }
                    }
                    if (rv - v).abs() > 1e-9 * v.abs().max(1.0) {
                        problems.push(format!("table {t} key {k:?}: rust {rv} != go {v}"));
                    }
                }
                None => problems.push(format!("table {t}: rust MISSING key {k:?} (go {v})")),
            }
        }

        for k in rust_map.keys() {
            if !go_map.contains_key(*k) {
                problems.push(format!("table {t}: rust EXTRA key {k:?} not in Go"));
            }
        }
    }

    assert!(
        problems.is_empty(),
        "default ratio tables diverge from Go ({} problems):\n{}",
        problems.len(),
        problems.join("\n")
    );
}
