/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=services/drain-source-registration-coordinator/wrangler.staging.jsonc --include-runtime=false --env-interface=DrainSourceRegistrationCoordinatorStagingEnv services/drain-source-registration-coordinator/worker-configuration.staging.d.ts` (hash: aba6cb5e08fd8588a45d298cefe8c10c)
interface __BaseEnv_DrainSourceRegistrationCoordinatorStagingEnv {
	CF_VERSION_METADATA: WorkerVersionMetadata;
	DRAIN_SOURCE_REGISTRATION_COORDINATOR_ENVIRONMENT: "staging";
	DRAIN_SOURCE_REGISTRATION_COORDINATOR_ENABLED: "false";
	DRAIN_SOURCE_REGISTRATION_COORDINATOR_AUTHORITY_ISSUER: "cinatoken-rust-api-staging";
	DRAIN_SOURCE_REGISTRATION_COORDINATOR_AUTHORITY_AUDIENCE: "cinatoken-drain-source-registration-coordinator-staging";
	DRAIN_SOURCE_REGISTRATION_COORDINATOR_CALLER_IDENTITY_SHA256: "";
	DRAIN_SOURCE_REGISTRATION_COORDINATOR_HMAC_CURRENT_KID: "";
	DRAIN_SOURCE_REGISTRATION_COORDINATOR_HMAC_PREVIOUS_KID: "";
	DRAIN_SOURCE_REGISTRATION_COORDINATORS: DurableObjectNamespace<import("./src/index").DrainSourceRegistrationCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "DrainSourceRegistrationCoordinator";
	}
	interface Env extends __BaseEnv_DrainSourceRegistrationCoordinatorStagingEnv {}
}
interface DrainSourceRegistrationCoordinatorStagingEnv extends __BaseEnv_DrainSourceRegistrationCoordinatorStagingEnv {}
