//! Bcrypt password hashing and verification.
//!
//! Mirrors the Go gateway's `common/crypto.go`:
//!
//! - `hash_password` ≡ Go `Password2Hash`, using `bcrypt::DEFAULT_COST`
//!   (which equals Go's `bcrypt.DefaultCost`).
//! - `verify_password` ≡ Go `ValidatePasswordAndHash`.
//!
//! Because both sides use the standard bcrypt PHB format (`$2a$…` / `$2b$…`),
//! hashes generated by the Go gateway verify unchanged in Rust and vice
//! versa. Existing users imported from a Go database can log in without a
//! password reset.

use bcrypt::{hash as bcrypt_hash, verify as bcrypt_verify, BcryptError, DEFAULT_COST};

/// Hash a plaintext password using bcrypt at default cost.
pub fn hash_password(password: &str) -> Result<String, BcryptError> {
    bcrypt_hash(password, DEFAULT_COST)
}

/// Verify a plaintext password against a stored bcrypt hash. Returns
/// `Ok(true)` on match and `Ok(false)` on mismatch (distinguished from a
/// malformed hash, which returns `Err`).
pub fn verify_password(password: &str, hash: &str) -> Result<bool, BcryptError> {
    bcrypt_verify(password, hash)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hash_and_verify_round_trip() {
        let hash = hash_password("correct horse battery staple").unwrap();
        assert!(verify_password("correct horse battery staple", &hash).unwrap());
        assert!(!verify_password("wrong password", &hash).unwrap());
    }

    #[test]
    fn hash_output_uses_bcrypt_phb_format() {
        let hash = hash_password("any").unwrap();
        assert!(
            hash.starts_with("$2a$") || hash.starts_with("$2b$") || hash.starts_with("$2y$"),
            "expected bcrypt PHB format, got {hash}"
        );
    }

    #[test]
    fn verify_rejects_empty_or_malformed_hash() {
        assert!(verify_password("anything", "").is_err());
        assert!(verify_password("anything", "not-a-bcrypt-hash").is_err());
    }
}
