[package]
name = "cinatoken-tasks"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
cinatoken-core = { path = "../core" }
hmac.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

