/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=services/drain-source-registration-permit-issuer/wrangler.staging.jsonc --include-runtime=false --env-interface=DrainSourceRegistrationPermitIssuerStagingEnv services/drain-source-registration-permit-issuer/worker-configuration.staging.d.ts` (hash: 2209b18808ae5123e67a32e8b6af3aac)
interface __BaseEnv_DrainSourceRegistrationPermitIssuerStagingEnv {
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "staging";
	DRAIN_SOURCE_REGISTRATION_PERMIT_ISSUER_ENABLED: "false";
	DRAIN_SOURCE_REGISTRATION_AUTHORITY_ISSUER: "cinatoken-relay-application-staging";
	DRAIN_SOURCE_REGISTRATION_AUTHORITY_AUDIENCE: "cinatoken-drain-source-registration-permit-issuer-staging";
	DRAIN_SOURCE_REGISTRATION_HMAC_CURRENT_KID: "";
	DRAIN_SOURCE_REGISTRATION_HMAC_CURRENT_CREDENTIAL_ID_SHA256: "";
	DRAIN_SOURCE_REGISTRATION_HMAC_PREVIOUS_KID: "";
	DRAIN_SOURCE_REGISTRATION_HMAC_PREVIOUS_CREDENTIAL_ID_SHA256: "";
	DRAIN_SOURCE_REGISTRATION_PERMIT_ISSUER: "cinatoken-drain-source-registration-permit-issuer-staging";
	DRAIN_SOURCE_REGISTRATION_PERMIT_AUDIENCE: "cinatoken-relay-application:staging:drain-source-registration:v1";
	DRAIN_SOURCE_REGISTRATION_PERMIT_KEY_ID: "";
	DRAIN_SOURCE_REGISTRATION_PERMIT_SIGNER_IDENTITY_SHA256: "";
	DRAIN_SOURCE_REGISTRATION_PERMIT_SPKI_SHA256: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_DrainSourceRegistrationPermitIssuerStagingEnv {}
}
interface DrainSourceRegistrationPermitIssuerStagingEnv extends __BaseEnv_DrainSourceRegistrationPermitIssuerStagingEnv {}
